---
abstract: 'Interface to RackSpace CloudServers via API'
author:
  - 'Marco Fontani'
generated_by: 'Dist::Zilla version 1.093400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-RackSpace-CloudServers
requires:
  Any::Moose: 0.10
  HTTP::Request: 0
  JSON: 0
  LWP::ConnCache::MaxKeepAliveRequests: 0
  LWP::UserAgent::Determined: 0
  YAML: 0
  perl: 5.010_000
version: 0.09_40
