---
abstract: 'Interface to RackSpace CloudServers via API'
author:
  - 'Marco Fontani'
generated_by: 'Dist::Zilla::Plugin::MetaYAML version 1.091940'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-RackSpace-CloudServers
requires:
  JSON: 0
  LWP::ConnCache::MaxKeepAliveRequests: 0
  LWP::UserAgent::Determined: 0
  Moose: 0.87
  MooseX::StrictConstructor: 0
  YAML: 0
version: 0.05_00
